application: comicfeeds-1022
version: 9
runtime: php55
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /view/(dilbert|pennyarcade)/(.+)
  script: scripts/view.php
  
- url: /fetch/(dilbert|pennyarcade)
  script: scripts/fetch.php

- url: /version
  script: scripts/version.php

- url: /.*
  static_files: index.html
  upload: index\.html
  
skip_files:
- ^tests/.*
- ^vendor/phpunit/.*
- ^vendor/bin/.*
- ^vendor/phpdocumentor/.*
- ^vendor/phpspec/.*
- ^vendor/sebastian/.*
- ^vendor/symfony/.*
- ^vendor/doctrine/.*