application: comicfeeds-1022
version: 2
runtime: php55
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /view/(dilbert|pennyarcade)/(.+)
  script: scripts/view.php
  
- url: /fetch/(dilbert|pennyarcade)/?
  script: scripts/fetch_\1.php

- url: /.*
  static_files: index.html
  upload: index\.html