# Guidance from: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
# Docs: https://github.com/marketplace/actions/docker-buildx
name: Build comicfeeds images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/comicfeeds:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
